# Note: this is for development purposes only
version: "2"
services:
  postgres:
    image: "postgres:11"
    # Create the file below and define POSTGRES_USER and POSTGRES_PASSWORD in it
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./secretshare.sql:/docker-entrypoint-initdb.d/secretshare.sql

  secretshareapi:
    image: "aardbol/secretshareapi:latest"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_USER}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
