#
# Copyright (c) 2020 Leonardo Malik <isaakm@pm.me>
#
# Licensed as open source under the EUROPEAN UNION PUBLIC LICENCE v. 1.2
# See LICENSE, LICENTIE or for other translations: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12
#
logging:
  level:
    .: warn
  file: secretshare.log